#!/usr/bin/env python3
"""Sutra pre-tool guard hook for Claude Code.

Generated by Sutra — do not edit directly. Run `sutra sync` to update.
Configuration is loaded from .sutra/hook-cache/guard-config.json at runtime.
"""

import json
import sys
import fnmatch
from datetime import datetime
from pathlib import Path


# ── Load configuration from .sutra/ at runtime ─────────────────────────


def _find_sutra_root():
    """Walk up from the hook file to find the .sutra directory."""
    hook_dir = Path(__file__).resolve().parent
    current = hook_dir.parent.parent  # .claude/hooks/ -> repo root
    for _ in range(5):
        if (current / ".sutra").is_dir():
            return current
        current = current.parent
    return hook_dir.parent.parent


_REPO_ROOT = _find_sutra_root()
_CONFIG_PATH = _REPO_ROOT / ".sutra" / "hook-cache" / "guard-config.json"

GUARD_ENABLED = False
DENY_PATTERNS = []
WARN_PATTERNS = []
DENY_WRITE_PATTERNS = []
ALLOW_WRITE_PATTERNS = []
FROZEN_PATHS = []

if _CONFIG_PATH.exists():
    try:
        with open(_CONFIG_PATH) as _f:
            _cfg = json.load(_f)
        GUARD_ENABLED = _cfg.get("guard_enabled", False)
        DENY_PATTERNS = _cfg.get("deny_patterns", [])
        WARN_PATTERNS = _cfg.get("warn_patterns", [])
        DENY_WRITE_PATTERNS = _cfg.get("deny_write_patterns", [])
        ALLOW_WRITE_PATTERNS = _cfg.get("allow_write_patterns", [])
        FROZEN_PATHS = _cfg.get("frozen_paths", [])
    except Exception:
        pass


def log_policy_event(event_type, details):
    """Log a policy event for evidence."""
    import fcntl

    evidence_dir = _REPO_ROOT / ".sutra" / "evidence"
    evidence_dir.mkdir(parents=True, exist_ok=True)
    log_file = evidence_dir / "policy-events.json"

    event = {
        "timestamp": datetime.utcnow().isoformat(),
        "type": event_type,
        "details": details,
    }

    with open(log_file, "a+", encoding="utf-8") as f:
        try:
            fcntl.flock(f, fcntl.LOCK_EX)
            f.seek(0)
            content = f.read().strip()
            if content:
                try:
                    events = json.loads(content)
                    if not isinstance(events, list):
                        events = []
                except Exception:
                    events = []
            else:
                events = []

            events.append(event)
            f.seek(0)
            f.truncate()
            json.dump(events, f, indent=2)
        finally:
            try:
                fcntl.flock(f, fcntl.LOCK_UN)
            except Exception:
                pass


# ── Hook logic ─────────────────────────────────────────────────────────


def _matches_pattern(command_lower, pattern):
    """Token-prefix + glob matching for command patterns."""
    cmd_tokens = command_lower.split()
    pat_tokens = pattern.lower().split()
    if cmd_tokens[: len(pat_tokens)] == pat_tokens:
        return True
    return fnmatch.fnmatch(command_lower, pattern.lower())


def check_command(command):
    """Check a command against policies."""
    if not GUARD_ENABLED:
        return {"allowed": True}

    command_lower = command.lower().strip()

    for pattern in DENY_PATTERNS:
        if _matches_pattern(command_lower, pattern):
            log_policy_event("BLOCKED", "Denied command: " + command)
            return {
                "allowed": False,
                "reason": "Blocked by Sutra policy: '"
                + pattern
                + "' is in the deny list.",
            }

    for pattern in WARN_PATTERNS:
        if _matches_pattern(command_lower, pattern):
            log_policy_event("WARNING", "Cautioned command: " + command)
            return {
                "allowed": True,
                "warning": "Sutra caution: '" + pattern + "' - proceed carefully.",
            }

    return {"allowed": True}


def check_file_path(file_path):
    """Check if a file path violates write restriction or frozen scope policies."""
    if not GUARD_ENABLED:
        return {"allowed": True}

    if DENY_WRITE_PATTERNS and any(
        fnmatch.fnmatch(file_path, pat) for pat in DENY_WRITE_PATTERNS
    ):
        log_policy_event(
            "BLOCKED", "Write restriction violation (deny list): " + file_path
        )
        return {
            "allowed": False,
            "reason": "Blocked by Sutra security policy: file '"
            + file_path
            + "' matches deny_write_patterns.",
        }
    if ALLOW_WRITE_PATTERNS and not any(
        fnmatch.fnmatch(file_path, pat) for pat in ALLOW_WRITE_PATTERNS
    ):
        log_policy_event(
            "BLOCKED", "Write restriction violation (not in allow list): " + file_path
        )
        return {
            "allowed": False,
            "reason": "Blocked by Sutra security policy: file '"
            + file_path
            + "' does not match allow_write_patterns.",
        }

    if FROZEN_PATHS:
        for allowed_path in FROZEN_PATHS:
            if file_path.startswith(allowed_path):
                return {"allowed": True}
        log_policy_event("BLOCKED", "File outside frozen scope: " + file_path)
        return {
            "allowed": False,
            "reason": "Blocked by Sutra guard: file '"
            + file_path
            + "' is outside the allowed scope: "
            + str(FROZEN_PATHS),
        }

    return {"allowed": True}


if __name__ == "__main__":
    input_data = json.loads(sys.stdin.read())
    tool_name = input_data.get("tool_name", "")
    tool_input = input_data.get("tool_input", {})

    result = {"allowed": True}

    if tool_name in ("bash", "shell", "terminal", "run_command"):
        command = tool_input.get("command", "") or tool_input.get("CommandLine", "")
        result = check_command(command)
    elif tool_name in (
        "write_file",
        "edit_file",
        "replace_file_content",
        "multi_replace_file_content",
    ):
        file_path = tool_input.get("file_path", "") or tool_input.get("TargetFile", "")
        result = check_file_path(file_path)

    print(json.dumps(result))
