"""Codex CLI runtime adapter — generates AGENTS.md."""

from __future__ import annotations

import json
import shutil
import yaml
from rich.console import Console

from niyam.runtimes.base import RuntimeAdapter


class CodexAdapter(RuntimeAdapter):
    """Adapter for OpenAI Codex CLI runtime."""

    @property
    def name(self) -> str:
        return "codex"

    def sync(self, console: Console) -> None:
        """Generate Codex CLI files from .niyam/ source of truth."""
        self._generate_agents_md(console)
        self._generate_hooks(console)
        self._generate_settings(console)
        console.print("[green]✓[/] Codex CLI runtime synced")

    def clean(self, console: Console) -> None:
        """Remove all Codex-generated files."""
        agents_md = self.repo_root / "AGENTS.md"
        codex_dir = self.repo_root / ".codex"
        if agents_md.exists():
            agents_md.unlink()
        if codex_dir.exists():
            shutil.rmtree(codex_dir)
        console.print("[yellow]♻ Removed Codex CLI files[/]")

    # ── Private generators ─────────────────────────────────────────────

    def _generate_agents_md(self, console: Console) -> None:
        """Generate AGENTS.md from .niyam/ source of truth."""
        sections: list[str] = []

        sections.append("# Agent Instructions")
        sections.append("")
        sections.append(
            "<!-- Generated by Niyam — do not edit directly. Run `niyam sync` to update. -->"
        )
        sections.append("")

        # Project context
        memory = self._read_niyam_file("context/project-memory.md")
        if memory:
            sections.append(memory)
            sections.append("")

        # Include memory files
        memory_dir = self.niyam_dir / "memory"
        if memory_dir.is_dir():
            for filepath in sorted(memory_dir.glob("*.md")):
                content = filepath.read_text(encoding="utf-8")
                if content.strip():
                    sections.append(content)
                    sections.append("")

        arch = self._read_niyam_file("context/architecture.md")
        if arch:
            sections.append(arch)
            sections.append("")

        validation = self._read_niyam_file("context/validation.md")
        if validation:
            sections.append(validation)
            sections.append("")

        # Available agents
        agents_section = self._build_agents_section()
        if agents_section:
            sections.append(agents_section)

        # Available skills
        skills_section = self._build_skills_section()
        if skills_section:
            sections.append(skills_section)

        # Policies
        policies_section = self._build_policies_section()
        if policies_section:
            sections.append(policies_section)

        # Write AGENTS.md
        agents_md = self.repo_root / "AGENTS.md"
        self._write_file(agents_md, "\n".join(sections), console)

    def _generate_settings(self, console: Console) -> None:
        """Generate .codex/settings.json."""
        settings_dir = self.repo_root / ".codex"

        tool_names = [
            "bash",
            "shell",
            "terminal",
            "run_command",
            "write_file",
            "edit_file",
            "replace_file_content",
            "multi_replace_file_content",
        ]
        pre_tool_use_hooks = []
        for tool in tool_names:
            pre_tool_use_hooks.append(
                {
                    "matcher": {"tool_name": tool},
                    "hook": {
                        "type": "command",
                        "command": "python .codex/hooks/pre_tool_guard.py",
                    },
                }
            )

        settings = {
            "project": self.repo_root.name,
            "runtime": "codex",
            "hooks": {"pre_tool_use": pre_tool_use_hooks},
        }

        settings_path = settings_dir / "settings.json"
        self._write_file(settings_path, json.dumps(settings, indent=2) + "\n", console)

    def _build_agents_section(self) -> str:
        """Build a section listing available agents."""
        agents = self._list_niyam_dir("agents")
        if not agents:
            return ""

        lines = ["## Available Agents", ""]
        for agent_file in agents:
            if agent_file.suffix == ".md":
                name = agent_file.stem.replace("-", " ").title()
                content = agent_file.read_text(encoding="utf-8")
                # Extract the first paragraph as description
                desc = ""
                for line in content.split("\n"):
                    line = line.strip()
                    if line and not line.startswith("#"):
                        desc = line
                        break
                lines.append(f"### {name}")
                if desc:
                    lines.append(desc)
                lines.append("")

        return "\n".join(lines)

    def _build_skills_section(self) -> str:
        """Build a section listing available skills."""
        skills_dir = self.niyam_dir / "skills"
        if not skills_dir.is_dir():
            return ""

        skill_dirs = [d for d in skills_dir.iterdir() if d.is_dir()]
        if not skill_dirs:
            return ""

        lines = ["## Available Skills", ""]
        for skill_dir in sorted(skill_dirs):
            skill_md = skill_dir / "SKILL.md"
            if skill_md.exists():
                content = skill_md.read_text(encoding="utf-8")
                name = skill_dir.name.replace("-", " ").title()
                # Extract description from frontmatter or first paragraph
                desc = ""
                for line in content.split("\n"):
                    line = line.strip()
                    if line and not line.startswith("#") and not line.startswith("---"):
                        desc = line
                        break
                lines.append(f"### {name}")
                if desc:
                    lines.append(desc)
                lines.append("")

        return "\n".join(lines)

    def _build_policies_section(self) -> str:
        """Build a policies section for Codex."""
        lines = ["## Policies", ""]

        cmd_policy = self._read_niyam_file("policies/commands.yaml")
        if cmd_policy:
            data = yaml.safe_load(cmd_policy) or {}
            deny = data.get("deny", [])
            if deny:
                lines.append("### Denied Commands")
                lines.append("Do NOT execute these commands:")
                for cmd in deny:
                    lines.append(f"- `{cmd}`")
                lines.append("")

        approval_policy = self._read_niyam_file("policies/approvals.yaml")
        if approval_policy:
            data = yaml.safe_load(approval_policy) or {}
            approvals = data.get("approval_required_for", [])
            if approvals:
                lines.append("### Approval Required")
                lines.append(
                    "Ask for human approval before making changes in these areas:"
                )
                for item in approvals:
                    lines.append(f"- {item.replace('_', ' ').title()}")
                lines.append("")

        return "\n".join(lines) if len(lines) > 2 else ""
