"""Claude Code runtime adapter — generates CLAUDE.md, .claude/ structure."""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import yaml
from rich.console import Console

from sutra.runtimes.base import RuntimeAdapter


class ClaudeAdapter(RuntimeAdapter):
    """Adapter for Claude Code runtime."""

    @property
    def name(self) -> str:
        return "claude"

    def sync(self, console: Console) -> None:
        """Generate Claude Code files from .sutra/ source of truth."""
        self._generate_claude_md(console)
        self._project_agents(console)
        self._project_commands(console)
        self._project_skills(console)
        self._generate_hooks(console)
        self._generate_settings(console)
        console.print(f"[green]✓[/] Claude Code runtime synced")

    def clean(self, console: Console) -> None:
        """Remove all Claude-generated files."""
        claude_md = self.repo_root / "CLAUDE.md"
        claude_dir = self.repo_root / ".claude"
        if claude_md.exists():
            claude_md.unlink()
        if claude_dir.exists():
            shutil.rmtree(claude_dir)
        console.print("[yellow]♻ Removed Claude Code files[/]")

    # ── Private generators ─────────────────────────────────────────────

    def _generate_claude_md(self, console: Console) -> None:
        """Generate CLAUDE.md from .sutra/context/ and .sutra/policies/."""
        sections: list[str] = []

        sections.append("# Project Instructions")
        sections.append("")
        sections.append("<!-- Generated by Sutra — do not edit directly. Run `sutra sync` to update. -->")
        sections.append("")

        # Include project memory
        memory = self._read_sutra_file("context/project-memory.md")
        if memory:
            sections.append(memory)
            sections.append("")

        # Include memory files
        memory_dir = self.sutra_dir / "memory"
        if memory_dir.is_dir():
            for filepath in sorted(memory_dir.glob("*.md")):
                content = filepath.read_text(encoding="utf-8")
                if content.strip():
                    sections.append(content)
                    sections.append("")

        # Include architecture
        arch = self._read_sutra_file("context/architecture.md")
        if arch:
            sections.append(arch)
            sections.append("")

        # Include validation commands
        validation = self._read_sutra_file("context/validation.md")
        if validation:
            sections.append(validation)
            sections.append("")

        # Include available commands
        commands_ref = self._read_sutra_file("context/commands.md")
        if commands_ref:
            sections.append(commands_ref)
            sections.append("")

        # Include policies summary
        policies_section = self._build_policies_section()
        if policies_section:
            sections.append(policies_section)

        # Write CLAUDE.md
        claude_md = self.repo_root / "CLAUDE.md"
        claude_md.write_text("\n".join(sections), encoding="utf-8")

    def _build_policies_section(self) -> str:
        """Build a markdown summary of active policies."""
        lines = ["## Policies", ""]

        # Command policy
        cmd_policy = self._read_sutra_file("policies/commands.yaml")
        if cmd_policy:
            data = yaml.safe_load(cmd_policy) or {}
            deny = data.get("deny", [])
            if deny:
                lines.append("### Denied Commands")
                lines.append("The following commands are **blocked** by Sutra policy:")
                for cmd in deny:
                    lines.append(f"- `{cmd}`")
                lines.append("")

            warn = data.get("warn", [])
            if warn:
                lines.append("### Warning Commands")
                lines.append("The following commands require **extra caution**:")
                for cmd in warn:
                    lines.append(f"- `{cmd}`")
                lines.append("")

        # Approval policy
        approval_policy = self._read_sutra_file("policies/approvals.yaml")
        if approval_policy:
            data = yaml.safe_load(approval_policy) or {}
            approvals = data.get("approval_required_for", [])
            if approvals:
                lines.append("### Approval Required")
                lines.append("The following changes require **human approval** before proceeding:")
                for item in approvals:
                    lines.append(f"- {item.replace('_', ' ').title()}")
                lines.append("")

        return "\n".join(lines) if len(lines) > 2 else ""

    def _project_agents(self, console: Console) -> None:
        """Copy .sutra/agents/ → .claude/agents/."""
        source_dir = self.sutra_dir / "agents"
        target_dir = self.repo_root / ".claude" / "agents"
        self._mirror_directory(source_dir, target_dir)

    def _project_commands(self, console: Console) -> None:
        """Copy .sutra/commands/ → .claude/commands/."""
        source_dir = self.sutra_dir / "commands"
        target_dir = self.repo_root / ".claude" / "commands"
        self._mirror_directory(source_dir, target_dir)

    def _project_skills(self, console: Console) -> None:
        """Copy .sutra/skills/ → .claude/skills/."""
        source_dir = self.sutra_dir / "skills"
        target_dir = self.repo_root / ".claude" / "skills"

        if not source_dir.is_dir():
            return

        target_dir.mkdir(parents=True, exist_ok=True)

        # Skills are directories, not files — copy recursively
        for skill_dir in source_dir.iterdir():
            if skill_dir.is_dir():
                target_skill = target_dir / skill_dir.name
                if target_skill.exists():
                    shutil.rmtree(target_skill)
                shutil.copytree(skill_dir, target_skill)

    def _generate_hooks(self, console: Console) -> None:
        """Generate .claude/hooks/pre_tool_guard.py from policies."""
        hooks_dir = self.repo_root / ".claude" / "hooks"
        hooks_dir.mkdir(parents=True, exist_ok=True)

        # Load command policy
        cmd_policy_content = self._read_sutra_file("policies/commands.yaml")
        deny_list: list[str] = []
        warn_list: list[str] = []

        if cmd_policy_content:
            data = yaml.safe_load(cmd_policy_content) or {}
            deny_list = data.get("deny", [])
            warn_list = data.get("warn", [])

        # Load security policy
        security_policy_content = self._read_sutra_file("policies/security.yaml")
        deny_write_patterns: list[str] = []
        allow_write_patterns: list[str] = []

        if security_policy_content:
            sec_data = yaml.safe_load(security_policy_content) or {}
            deny_write_patterns = sec_data.get("deny_write_patterns", [])
            allow_write_patterns = sec_data.get("allow_write_patterns", [])

        # Load guard state
        sutra_config_content = self._read_sutra_file("sutra.yaml")
        frozen_paths: list[str] = []
        guard_enabled = False
        remote_policy_url: str | None = None

        if sutra_config_content:
            config_data = yaml.safe_load(sutra_config_content) or {}
            guard = config_data.get("guard", {})
            guard_enabled = guard.get("enabled", False)
            frozen_paths = guard.get("frozen_paths", [])
            remote_policy_url = guard.get("remote_policy_url")

        hook_content = self._render_hook_script(
            deny_list,
            warn_list,
            deny_write_patterns,
            allow_write_patterns,
            frozen_paths,
            guard_enabled,
            remote_policy_url,
        )
        hook_path = hooks_dir / "pre_tool_guard.py"
        hook_path.write_text(hook_content, encoding="utf-8")

    def _render_hook_script(
        self,
        deny_list: list[str],
        warn_list: list[str],
        deny_write_patterns: list[str],
        allow_write_patterns: list[str],
        frozen_paths: list[str],
        guard_enabled: bool,
        remote_policy_url: str | None,
    ) -> str:
        """Render the pre-tool guard hook script."""
        return f'''#!/usr/bin/env python3
"""Sutra pre-tool guard hook for Claude Code.

Generated by Sutra — do not edit directly. Run `sutra sync` to update.
"""

import json
import sys
import os
import fnmatch
from datetime import datetime

# ── Configuration ──────────────────────────────────────────────────────

GUARD_ENABLED = {guard_enabled}

REMOTE_POLICY_URL = {json.dumps(remote_policy_url)}

DENY_PATTERNS = {json.dumps(deny_list, indent=4)}

WARN_PATTERNS = {json.dumps(warn_list, indent=4)}

DENY_WRITE_PATTERNS = {json.dumps(deny_write_patterns, indent=4)}

ALLOW_WRITE_PATTERNS = {json.dumps(allow_write_patterns, indent=4)}

FROZEN_PATHS = {json.dumps(frozen_paths, indent=4)}

# Try to load remote patterns if configured
if GUARD_ENABLED and REMOTE_POLICY_URL:
    try:
        import urllib.request
        import yaml
        
        # 1. Fetch commands.yaml
        if REMOTE_POLICY_URL.endswith(".yaml") or REMOTE_POLICY_URL.endswith(".yml"):
            target_cmd_url = REMOTE_POLICY_URL
            if "security.yaml" in target_cmd_url:
                target_cmd_url = target_cmd_url.replace("security.yaml", "commands.yaml")
        else:
            target_cmd_url = f"{{REMOTE_POLICY_URL.rstrip('/')}}/commands.yaml"
            
        req_cmd = urllib.request.Request(target_cmd_url, headers={{"User-Agent": "Sutra-CLI"}})
        with urllib.request.urlopen(req_cmd, timeout=2) as response:
            cmd_data = yaml.safe_load(response.read().decode("utf-8")) or {{}}
            if "deny" in cmd_data:
                DENY_PATTERNS = cmd_data["deny"]
            if "warn" in cmd_data:
                WARN_PATTERNS = cmd_data["warn"]
    except Exception:
        pass

    try:
        import urllib.request
        import yaml
        
        # 2. Fetch security.yaml
        if REMOTE_POLICY_URL.endswith(".yaml") or REMOTE_POLICY_URL.endswith(".yml"):
            target_sec_url = REMOTE_POLICY_URL
            if "commands.yaml" in target_sec_url:
                target_sec_url = target_sec_url.replace("commands.yaml", "security.yaml")
        else:
            target_sec_url = f"{{REMOTE_POLICY_URL.rstrip('/')}}/security.yaml"
            
        req_sec = urllib.request.Request(target_sec_url, headers={{"User-Agent": "Sutra-CLI"}})
        with urllib.request.urlopen(req_sec, timeout=2) as response:
            sec_data = yaml.safe_load(response.read().decode("utf-8")) or {{}}
            if "deny_write_patterns" in sec_data:
                DENY_WRITE_PATTERNS = sec_data["deny_write_patterns"]
            if "allow_write_patterns" in sec_data:
                ALLOW_WRITE_PATTERNS = sec_data["allow_write_patterns"]
    except Exception:
        pass

# ── Evidence logging ───────────────────────────────────────────────────

def log_policy_event(event_type: str, details: str) -> None:
    """Log a policy event for evidence."""
    evidence_dir = os.path.join(os.path.dirname(__file__), "..", "..", ".sutra", "evidence")
    os.makedirs(evidence_dir, exist_ok=True)

    log_file = os.path.join(evidence_dir, "policy-events.json")
    event = {{
        "timestamp": datetime.utcnow().isoformat(),
        "type": event_type,
        "details": details,
    }}

    events = []
    if os.path.exists(log_file):
        try:
            with open(log_file) as f:
                events = json.load(f)
        except (json.JSONDecodeError, FileNotFoundError):
            events = []

    events.append(event)

    with open(log_file, "w") as f:
        json.dump(events, f, indent=2)

# ── Hook logic ─────────────────────────────────────────────────────────

def check_command(command: str) -> dict:
    """Check a command against policies."""
    if not GUARD_ENABLED:
        return {{"allowed": True}}

    command_lower = command.lower().strip()

    # Check deny list
    for pattern in DENY_PATTERNS:
        if pattern.replace("*", "") in command_lower or command_lower.startswith(pattern.split("*")[0].strip()):
            log_policy_event("BLOCKED", f"Denied command: {{command}}")
            return {{
                "allowed": False,
                "reason": f"🛑 Blocked by Sutra policy: '{{pattern}}' is in the deny list.",
            }}

    # Check warn list
    for pattern in WARN_PATTERNS:
        if pattern.replace("*", "") in command_lower or command_lower.startswith(pattern.split("*")[0].strip()):
            log_policy_event("WARNING", f"Cautioned command: {{command}}")
            return {{
                "allowed": True,
                "warning": f"⚠️  Sutra caution: '{{pattern}}' — proceed carefully.",
            }}

    return {{"allowed": True}}


def check_file_path(file_path: str) -> dict:
    """Check if a file path violates write restriction or frozen scope policies."""
    if not GUARD_ENABLED:
        return {{"allowed": True}}

    # Enforce write restriction policies
    if DENY_WRITE_PATTERNS and any(fnmatch.fnmatch(file_path, pat) for pat in DENY_WRITE_PATTERNS):
        log_policy_event("BLOCKED", f"Write restriction violation (deny list): {{file_path}}")
        return {{
            "allowed": False,
            "reason": f"🛑 Blocked by Sutra security policy: file '{{file_path}}' matches deny_write_patterns.",
        }}
    if ALLOW_WRITE_PATTERNS and not any(fnmatch.fnmatch(file_path, pat) for pat in ALLOW_WRITE_PATTERNS):
        log_policy_event("BLOCKED", f"Write restriction violation (not in allow list): {{file_path}}")
        return {{
            "allowed": False,
            "reason": f"🛑 Blocked by Sutra security policy: file '{{file_path}}' does not match allow_write_patterns.",
        }}

    # Enforce frozen paths
    if FROZEN_PATHS:
        for allowed_path in FROZEN_PATHS:
            if file_path.startswith(allowed_path):
                return {{"allowed": True}}
        log_policy_event("BLOCKED", f"File outside frozen scope: {{file_path}}")
        return {{
            "allowed": False,
            "reason": f"🛑 Blocked by Sutra guard: file '{{file_path}}' is outside the allowed scope: {{FROZEN_PATHS}}",
        }}

    return {{"allowed": True}}


if __name__ == "__main__":
    # Read hook input from stdin
    input_data = json.loads(sys.stdin.read())
    tool_name = input_data.get("tool_name", "")
    tool_input = input_data.get("tool_input", {{}})

    result = {{"allowed": True}}

    # Check command executions
    if tool_name in ("bash", "shell", "terminal", "run_command"):
        command = tool_input.get("command", "") or tool_input.get("CommandLine", "")
        result = check_command(command)

    # Check file writes
    elif tool_name in ("write_file", "edit_file", "replace_file_content", "multi_replace_file_content"):
        file_path = tool_input.get("file_path", "") or tool_input.get("TargetFile", "")
        result = check_file_path(file_path)

    print(json.dumps(result))
'''


    def _generate_settings(self, console: Console) -> None:
        """Generate .claude/settings.json."""
        settings_dir = self.repo_root / ".claude"
        settings_dir.mkdir(parents=True, exist_ok=True)

        settings = {
            "hooks": {
                "pre_tool_use": [
                    {
                        "matcher": {"tool_name": "bash"},
                        "hook": {
                            "type": "command",
                            "command": "python .claude/hooks/pre_tool_guard.py",
                        },
                    }
                ]
            }
        }

        settings_path = settings_dir / "settings.json"
        settings_path.write_text(
            json.dumps(settings, indent=2) + "\n",
            encoding="utf-8",
        )

    def _mirror_directory(self, source: Path, target: Path) -> None:
        """Mirror a source directory to a target, removing stale files."""
        if not source.is_dir():
            return

        target.mkdir(parents=True, exist_ok=True)

        # Copy source files
        for src_file in source.iterdir():
            if src_file.is_file():
                dst_file = target / src_file.name
                shutil.copy2(src_file, dst_file)
