"""Claude Code runtime adapter — generates CLAUDE.md, .claude/ structure."""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import yaml
from rich.console import Console

from sutra.runtimes.base import RuntimeAdapter


class ClaudeAdapter(RuntimeAdapter):
    """Adapter for Claude Code runtime."""

    @property
    def name(self) -> str:
        return "claude"

    def sync(self, console: Console) -> None:
        """Generate Claude Code files from .sutra/ source of truth."""
        self._generate_claude_md(console)
        self._project_agents(console)
        self._project_commands(console)
        self._project_skills(console)
        self._generate_hooks(console)
        self._generate_settings(console)
        console.print("[green]✓[/] Claude Code runtime synced")

    def clean(self, console: Console) -> None:
        """Remove all Claude-generated files."""
        claude_md = self.repo_root / "CLAUDE.md"
        claude_dir = self.repo_root / ".claude"
        if claude_md.exists():
            claude_md.unlink()
        if claude_dir.exists():
            shutil.rmtree(claude_dir)
        console.print("[yellow]♻ Removed Claude Code files[/]")

    # ── Private generators ─────────────────────────────────────────────

    def _generate_claude_md(self, console: Console) -> None:
        """Generate CLAUDE.md from .sutra/context/ and .sutra/policies/."""
        sections: list[str] = []

        sections.append("# Project Instructions")
        sections.append("")
        sections.append(
            "<!-- Generated by Sutra — do not edit directly. Run `sutra sync` to update. -->"
        )
        sections.append("")

        # Include project memory
        memory = self._read_sutra_file("context/project-memory.md")
        if memory:
            sections.append(memory)
            sections.append("")

        # Include memory files
        memory_dir = self.sutra_dir / "memory"
        if memory_dir.is_dir():
            for filepath in sorted(memory_dir.glob("*.md")):
                content = filepath.read_text(encoding="utf-8")
                if content.strip():
                    sections.append(content)
                    sections.append("")

        # Include architecture
        arch = self._read_sutra_file("context/architecture.md")
        if arch:
            sections.append(arch)
            sections.append("")

        # Include validation commands
        validation = self._read_sutra_file("context/validation.md")
        if validation:
            sections.append(validation)
            sections.append("")

        # Include available commands
        commands_ref = self._read_sutra_file("context/commands.md")
        if commands_ref:
            sections.append(commands_ref)
            sections.append("")

        # Include policies summary
        policies_section = self._build_policies_section()
        if policies_section:
            sections.append(policies_section)

        # Write CLAUDE.md
        claude_md = self.repo_root / "CLAUDE.md"
        self._write_file(claude_md, "\n".join(sections), console)

    def _build_policies_section(self) -> str:
        """Build a markdown summary of active policies."""
        lines = ["## Policies", ""]

        # Command policy
        cmd_policy = self._read_sutra_file("policies/commands.yaml")
        if cmd_policy:
            data = yaml.safe_load(cmd_policy) or {}
            deny = data.get("deny", [])
            if deny:
                lines.append("### Denied Commands")
                lines.append("The following commands are **blocked** by Sutra policy:")
                for cmd in deny:
                    lines.append(f"- `{cmd}`")
                lines.append("")

            warn = data.get("warn", [])
            if warn:
                lines.append("### Warning Commands")
                lines.append("The following commands require **extra caution**:")
                for cmd in warn:
                    lines.append(f"- `{cmd}`")
                lines.append("")

        # Approval policy
        approval_policy = self._read_sutra_file("policies/approvals.yaml")
        if approval_policy:
            data = yaml.safe_load(approval_policy) or {}
            approvals = data.get("approval_required_for", [])
            if approvals:
                lines.append("### Approval Required")
                lines.append(
                    "The following changes require **human approval** before proceeding:"
                )
                for item in approvals:
                    lines.append(f"- {item.replace('_', ' ').title()}")
                lines.append("")

        return "\n".join(lines) if len(lines) > 2 else ""

    def _project_agents(self, console: Console) -> None:
        """Copy .sutra/agents/ → .claude/agents/."""
        source_dir = self.sutra_dir / "agents"
        target_dir = self.repo_root / ".claude" / "agents"
        self._mirror_directory(source_dir, target_dir, console)

    def _project_commands(self, console: Console) -> None:
        """Copy .sutra/commands/ → .claude/commands/."""
        source_dir = self.sutra_dir / "commands"
        target_dir = self.repo_root / ".claude" / "commands"
        self._mirror_directory(source_dir, target_dir, console)

    def _project_skills(self, console: Console) -> None:
        """Copy .sutra/skills/ → .claude/skills/."""
        source_dir = self.sutra_dir / "skills"
        target_dir = self.repo_root / ".claude" / "skills"

        if not source_dir.is_dir():
            return

        if not self.dry_run:
            target_dir.mkdir(parents=True, exist_ok=True)

        # Skills are directories, not files — copy recursively
        for skill_dir in source_dir.iterdir():
            if skill_dir.is_dir():
                target_skill = target_dir / skill_dir.name
                self._mirror_directory(skill_dir, target_skill, console)

    def _generate_settings(self, console: Console) -> None:
        """Generate .claude/settings.json."""
        settings_dir = self.repo_root / ".claude"

        tool_names = [
            "bash",
            "shell",
            "terminal",
            "run_command",
            "write_file",
            "edit_file",
            "replace_file_content",
            "multi_replace_file_content",
        ]
        pre_tool_use_hooks = []
        for tool in tool_names:
            pre_tool_use_hooks.append(
                {
                    "matcher": {"tool_name": tool},
                    "hook": {
                        "type": "command",
                        "command": "python .claude/hooks/pre_tool_guard.py",
                    },
                }
            )

        settings = {"hooks": {"pre_tool_use": pre_tool_use_hooks}}
        settings_path = settings_dir / "settings.json"
        self._write_file(settings_path, json.dumps(settings, indent=2) + "\n", console)
