"""Gemini CLI runtime adapter — generates GEMINI.md, .gemini/ structure."""

from __future__ import annotations

import json
import shutil

import yaml
from rich.console import Console

from sutra.runtimes.base import RuntimeAdapter


class GeminiAdapter(RuntimeAdapter):
    """Adapter for Google Gemini CLI runtime."""

    @property
    def name(self) -> str:
        return "gemini"

    def sync(self, console: Console) -> None:
        """Generate Gemini CLI files from .sutra/ source of truth."""
        self._generate_gemini_md(console)
        self._generate_style_md(console)
        self._generate_settings(console)
        console.print("[green]✓[/] Gemini CLI runtime synced")

    def clean(self, console: Console) -> None:
        """Remove all Gemini-generated files."""
        gemini_md = self.repo_root / "GEMINI.md"
        gemini_dir = self.repo_root / ".gemini"
        if gemini_md.exists():
            gemini_md.unlink()
        if gemini_dir.exists():
            shutil.rmtree(gemini_dir)
        console.print("[yellow]♻ Removed Gemini CLI files[/]")

    # ── Private generators ─────────────────────────────────────────────

    def _generate_gemini_md(self, console: Console) -> None:
        """Generate GEMINI.md from .sutra/context/ and .sutra/policies/."""
        sections: list[str] = []

        sections.append("# Gemini Project Instructions")
        sections.append("")
        sections.append(
            "<!-- Generated by Sutra — do not edit directly. Run `sutra sync` to update. -->"
        )
        sections.append("")

        # Include project memory
        memory = self._read_sutra_file("context/project-memory.md")
        if memory:
            sections.append(memory)
            sections.append("")

        # Include memory files
        memory_dir = self.sutra_dir / "memory"
        if memory_dir.is_dir():
            for filepath in sorted(memory_dir.glob("*.md")):
                content = filepath.read_text(encoding="utf-8")
                if content.strip():
                    sections.append(content)
                    sections.append("")

        # Include architecture
        arch = self._read_sutra_file("context/architecture.md")
        if arch:
            sections.append(arch)
            sections.append("")

        # Include validation commands
        validation = self._read_sutra_file("context/validation.md")
        if validation:
            sections.append(validation)
            sections.append("")

        # Include available commands
        commands_ref = self._read_sutra_file("context/commands.md")
        if commands_ref:
            sections.append(commands_ref)
            sections.append("")

        # Include policies summary
        policies_section = self._build_policies_section()
        if policies_section:
            sections.append(policies_section)

        # Write GEMINI.md
        gemini_md = self.repo_root / "GEMINI.md"
        gemini_md.write_text("\n".join(sections), encoding="utf-8")

    def _generate_style_md(self, console: Console) -> None:
        """Generate .gemini/STYLE.md with Gemini-compatible guidelines."""
        style_dir = self.repo_root / ".gemini"
        style_dir.mkdir(parents=True, exist_ok=True)

        content = """# Gemini Style & Development Guidelines

Generated by Sutra. Follow these rules when developing in this project:

## General Development Rules

1. **Be rigorous**: Verify code builds and passes linters after any changes.
2. **Write clean prose**: Ensure code comments are clear and docs match implementation.
3. **Follow architecture**: Adhere to established project design patterns.
"""
        style_md = style_dir / "STYLE.md"
        style_md.write_text(content, encoding="utf-8")

    def _generate_settings(self, console: Console) -> None:
        """Generate .gemini/settings.json."""
        settings_dir = self.repo_root / ".gemini"
        settings_dir.mkdir(parents=True, exist_ok=True)

        settings = {"project": self.repo_root.name, "runtime": "gemini", "sync": True}

        settings_path = settings_dir / "settings.json"
        settings_path.write_text(
            json.dumps(settings, indent=2) + "\n",
            encoding="utf-8",
        )

    def _build_policies_section(self) -> str:
        """Build a policies section for Gemini."""
        lines = ["## Policies", ""]

        cmd_policy = self._read_sutra_file("policies/commands.yaml")
        if cmd_policy:
            data = yaml.safe_load(cmd_policy) or {}
            deny = data.get("deny", [])
            if deny:
                lines.append("### Denied Commands")
                lines.append("Do NOT execute these commands:")
                for cmd in deny:
                    lines.append(f"- `{cmd}`")
                lines.append("")

        approval_policy = self._read_sutra_file("policies/approvals.yaml")
        if approval_policy:
            data = yaml.safe_load(approval_policy) or {}
            approvals = data.get("approval_required_for", [])
            if approvals:
                lines.append("### Approval Required")
                lines.append(
                    "Ask for human approval before making changes in these areas:"
                )
                for item in approvals:
                    lines.append(f"- {item.replace('_', ' ').title()}")
                lines.append("")

        return "\n".join(lines) if len(lines) > 2 else ""
